pipeline {
    agent any

    stages {
        stage('Clonar o repositório') {
            steps {
                git branch: 'main', url: 'https://github.com/AdrianoSilva130/ExercicioTesteAPI.git'

            }
        }
        stage('Instalar dependencias') {
            steps {
               bat 'npm test'
            }
        }
    stage ('Executar Testes'){
        steps {
            bat 'NO_COLOR=1
            npm run cy:run'
        }
    }
    
    }

}